"""`dossier demo` -- the canonical end-to-end run.

One deal, three questions chosen to exercise three different paths, then a memo:

  1. a question answerable from filing text alone       -> search_filings, [E#] citations
  2. a question needing exact figures and arithmetic    -> get_financials + compute, [F#]/[C#]
  3. a question about a company outside the corpus      -> abstention, no citations

Then `memo`, which runs five section sub-agents concurrently and synthesizes them.

The deal is written to `data/demo_deal.json` and committed, so the README's trace tree and
memo excerpt can be regenerated by anyone with an API key rather than being screenshots of
a run nobody else can reproduce.
"""

from __future__ import annotations

import asyncio
import json
import time

from .config import get_config

DEMO_DEAL_ID = "deal_demo_costco"

DEMO_QUESTIONS = [
    {
        "kind": "text_lookup",
        "question": "What does Costco's FY2021 10-K say about how membership fee revenue is recognized, and what does it disclose about renewal rates?",
        "expect": "an answer citing filing passages [E#]",
    },
    {
        "kind": "financials_and_compute",
        "question": "What was Costco's free cash flow in FY2021? Use the XBRL facts for operating cash flow and capital expenditure, and compute the difference.",
        "expect": "an answer citing XBRL facts [F#] and a computed value [C#]",
    },
    {
        "kind": "out_of_corpus",
        "question": "What was Kroger's FY2021 gross margin?",
        "expect": "an abstention -- Kroger is not in the indexed corpus",
    },
]


def build_demo_deal() -> dict:
    """Pick the demo deal from the manifest: a sector with at least three companies present."""
    from .ingest.financebench import load_manifest

    manifest = load_manifest()
    docs = manifest["documents"]
    by_sector: dict[str, set[str]] = {}
    for d in docs:
        by_sector.setdefault(d.get("gics_sector") or "", set()).add(d["company"])
    # Consumer Staples: Costco has a 10-K in the corpus and shares the sector with several
    # peers, which is what makes compare_peers and the graph channel do real work.
    payload = {
        "id": DEMO_DEAL_ID,
        "target": "Costco",
        "peers": sorted(c for c in by_sector.get("Consumer Staples", set()) if c != "Costco")[:3],
        "thesis": (
            "Screen Costco as a membership-model retail asset: how durable is the fee stream, "
            "how capital-intensive is the store base, and how does it compare with staples peers."
        ),
        "sector": "Consumer Staples",
        "questions": DEMO_QUESTIONS,
    }
    if not payload["peers"]:
        payload["peers"] = sorted({d["company"] for d in docs if d["company"] != "Costco"})[:3]
    get_config().paths.demo_deal.write_text(json.dumps(payload, indent=2))
    return payload


def run_demo(sequential: bool = False) -> dict:
    from .agent.deal import create_deal, get_deal
    from .agent.loop import ask
    from .agent.subagents import memo

    spec = build_demo_deal()
    try:
        deal = get_deal(DEMO_DEAL_ID)
    except KeyError:
        deal = create_deal(target=spec["target"], peers=spec["peers"], thesis=spec["thesis"], deal_id=DEMO_DEAL_ID)

    started = time.time()
    asks = []
    for q in DEMO_QUESTIONS:
        result = ask(deal, q["question"])
        asks.append(
            {
                "kind": q["kind"],
                "question": q["question"],
                "expect": q["expect"],
                "run_id": result.run_id,
                "state": result.state,
                "answer": result.answer_markdown,
                "evidence_ids": result.evidence_ids,
                "guard_pass": result.guard_pass,
                "turns": result.turns,
                "cost_usd": round(result.cost_usd, 6),
                "elapsed_s": result.elapsed_s,
                "tools": [e.get("tool") for e in result.events if e.get("type") == "tool_call"],
            }
        )

    memo_result = asyncio.run(memo(deal, sequential=sequential))
    report = {
        "deal_id": deal.id,
        "target": deal.target,
        "peers": deal.peers,
        "asks": asks,
        "memo": {
            "run_id": memo_result["run_id"],
            "state": memo_result["state"],
            "sections": [s["section"] for s in memo_result["sections"]],
            "evidence_count": memo_result["evidence_count"],
            "guard_pass": memo_result["guard_pass"],
            "cost_usd": memo_result["cost_usd"],
            "elapsed_s": memo_result["elapsed_s"],
            "sequential": sequential,
            "markdown": memo_result["markdown"],
            "pending_reviews": memo_result["pending_reviews"],
        },
        "total_cost_usd": round(sum(a["cost_usd"] for a in asks) + memo_result["cost_usd"], 6),
        "elapsed_s": round(time.time() - started, 1),
    }
    (get_config().paths.reports / "demo.json").write_text(json.dumps(report, indent=2, default=str))
    return report
